# Generated by Django 2.2.1 on 2019-05-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='author',
            new_name='identity',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='title',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='content',
        ),
        migrations.RemoveField(
            model_name='login',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='login',
            name='update_time',
        ),
    ]
